version: "3"

services:
  smart-brain-api:
    container_name: backend
    build: .
    command: npm start
    working_dir: /usr/src/smart-brain-api
    ports:
      - "3003:3003"
    volumes:
      - ./:/usr/src/smart-brain-api
